src/Entity/PFile.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PFileRepository")
 */
class PFile
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $FileName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Project", inversedBy="pictures")
     */
    private $project;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFileName(): ?string
    {
        return $this->FileName;
    }

    public function setFileName(string $FileName): self
    {
        $this->FileName = $FileName;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getProject(): ?Project
    {
        return $this->project;
    }

    public function setProject(?Project $project): self
    {
        $this->project = $project;

        return $this;
    }
}

templates/file/_delete_form.html.twig
<form method="post" action="{{ path('file_delete', {'id': file.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ file.id) }}">
    <button class="btn">Delete</button>
</form>

templates/file/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_row(form.pFile) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/file/edit.html.twig
{% extends 'adminBase.html.twig' %}

{% block title %}Edit File{% endblock %}

{% block body2 %}
    <h1>Edit File</h1>

    {{ include('file/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('file_index') }}">back to list</a>

    {{ include('file/_delete_form.html.twig') }}
{% endblock %}

templates/file/index.html.twig
{% extends 'adminBase.html.twig' %}

{% block title %}File index{% endblock %}

{% block body2 %}
    <h1>File index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>FileName</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for file in files %}
            <tr>
                <td>{{ file.id }}</td>
                <td>{{ file.name }}</td>
                <td>{{ file.FileName }}</td>
                <td>
                    <a href="{{ path('file_show', {'id': file.id}) }}">show</a>
                    <a href="{{ path('file_edit', {'id': file.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('file_new') }}">Create new</a>
{% endblock %}

templates/file/new.html.twig
{% extends 'adminBase.html.twig' %}

{% block title %}New File{% endblock %}

{% block body2 %}
    <h1>Create new File</h1>

    {{ include('file/_form.html.twig') }}

    <a href="{{ path('file_index') }}">back to list</a>
{% endblock %}

templates/file/show.html.twig
{% extends 'adminBase.html.twig' %}

{% block title %}File{% endblock %}

{% block body2 %}
    <h1>File</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ file.id }}</td>
            </tr>
            <tr>
                <th>FileName</th>
                <td>{{ file.FileName }}</td>
            </tr>
        </tbody>
    </table>

    <img src="/uploads/files/{{file.fileName}}" alt="" class="img-fluid">

    <a href="{{ path('file_index') }}">back to list</a>

    <a href="{{ path('file_edit', {'id': file.id}) }}">edit</a>

    {{ include('file/_delete_form.html.twig') }}
{% endblock %}